// Generated by Lasy AI - https://lasy.ai
"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { useEffect } from "react";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { setupGlobalAuthErrorHandler } from "../lib/authErrorHandler";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // Só configurar no cliente
    if (typeof window !== 'undefined') {
      setupGlobalAuthErrorHandler()
    }
  }, [])

  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <title>Novita - Seu Catálogo de Tênis Online</title>
        <meta name="description" content="Encontre os melhores tênis Nike e Adidas com design moderno e qualidade garantida. Catálogo online com variedade de cores e modelos." />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}